# Generated by Django 4.2.7 on 2023-12-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('emailone', models.EmailField(max_length=254)),
                ('userna', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=100)),
            ],
        ),
    ]
