# Generated by Django 4.2.7 on 2023-12-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app1', '0002_regmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminimagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aimage', models.FileField(upload_to='image_app1/static')),
                ('aimagename', models.CharField(max_length=100)),
            ],
        ),
    ]
